<a href="https://colab.research.google.com/github/Davioliveira1305/PyTorch/blob/main/TitanicRedeNeural.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estrutura da Rede Neural

In [186]:
import torch
import pandas as pd
import numpy as np
from torch import nn
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [187]:
class Rede(nn.Module):
  def __init__(self):
    super().__init__()
    self.layers = nn.Sequential(
        nn.Linear(12, 64),
        nn.ReLU(),
        nn.Linear(64, 26),
        nn.ReLU(),
        nn.Linear(26, 2)
    )

  def forward(self, x):
    return self.layers(x)

# Pr√©-Processamento dos dados

In [188]:
data = pd.read_csv('/content/titanic.csv')

In [189]:
data = data.dropna() # Exclui as linhas possuem valores NaN
data['Age'] = data['Age'].astype(int) # Transformar o tipo da coluna Age para inteiro
le = LabelEncoder()
data['Sex'] = le.fit_transform(data['Sex'])
data['Embarked'] = le.fit_transform(data['Embarked'])
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38,1,0,PC 17599,71.2833,C85,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35,1,0,113803,53.1000,C123,2
6,7,0,1,"McCarthy, Mr. Timothy J",1,54,0,0,17463,51.8625,E46,2
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",0,4,1,1,PP 9549,16.7000,G6,2
11,12,1,1,"Bonnell, Miss. Elizabeth",0,58,0,0,113783,26.5500,C103,2
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",0,47,1,1,11751,52.5542,D35,2
872,873,0,1,"Carlsson, Mr. Frans Olof",1,33,0,0,695,5.0000,B51 B53 B55,2
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",0,56,0,1,11767,83.1583,C50,0
887,888,1,1,"Graham, Miss. Margaret Edith",0,19,0,0,112053,30.0000,B42,2
889,890,1,1,"Behr, Mr. Karl Howell",1,26,0,0,111369,30.0000,C148,0

In [190]:
dum = pd.get_dummies(data['Embarked']) # Dividindo a coluna 'Embarked' em 3 novas colunas
data = pd.concat([data,dum], axis=1) # Colocando as novas colunas no DataFrame
data = data.drop('Embarked', axis='columns') # Dropando a antiga coluna 'Embarked'

data = data.rename(columns={2: 'Southampton', 0:'Cherbourg', 1:'Queenstown'}) # Renomeando as colunas

In [191]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Cherbourg,Queenstown,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38,1,0,PC 17599,71.2833,C85,1,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35,1,0,113803,53.1000,C123,0,0,1
6,7,0,1,"McCarthy, Mr. Timothy J",1,54,0,0,17463,51.8625,E46,0,0,1
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",0,4,1,1,PP 9549,16.7000,G6,0,0,1
11,12,1,1,"Bonnell, Miss. Elizabeth",0,58,0,0,113783,26.5500,C103,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",0,47,1,1,11751,52.5542,D35,0,0,1
872,873,0,1,"Carlsson, Mr. Frans Olof",1,33,0,0,695,5.0000,B51 B53 B55,0,0,1
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",0,56,0,1,11767,83.1583,C50,1,0,0
887,888,1,1,"Graham, Miss. Margaret Edith",0,19,0,0,112053,30.0000,B42,0,0,1
889,890,1,1,"Behr, Mr. Karl Howell",1,26,0,0,111369,30.0000,C148,1,0,0

In [192]:
dum2 = pd.get_dummies(data['Pclass']) # Dividindo a coluna 'Pclass' em 3 novas colunas
data = pd.concat([data,dum2], axis=1) # Colocando novas colunas no DataFrame
data = data.drop('Pclass', axis='columns') # Dropando a antiga coluna 'Pclass'
data = data.rename(columns={3:'Class3a', 2:'Class2a', 1:'Class1a'}) # Renomeando as colunas
data = data.drop('Name', axis = 'columns') # Dropando a coluna Name
data = data.drop('Ticket', axis = 'columns') # Dropando a coluna Ticket
data = data.drop('Cabin', axis = 'columns') # Dropando a coluna Cabin

In [193]:
data['Survived']

1      1
3      1
6      0
10     1
11     1
      ..
871    1
872    0
879    1
887    1
889    1
Name: Survived, Length: 183, dtype: int64

# Definindo a estrutura dos dados

In [194]:
import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from sklearn.model_selection import train_test_split

class MeuDataset(Dataset):
    def __init__(self, data, label_column, train = True):
        self.data = data
        self.label_column = label_column

        # Dividir os dados em conjuntos de treinamento e teste
        train_indices, test_indices = train_test_split(range(len(self.data)), test_size=0.2, random_state=42)

        # Selecionar √≠ndices apropriados com base no modo (treinamento ou teste)
        if train:
            self.indices = train_indices
        else:
            self.indices = test_indices


    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        sample = self.data.iloc[self.indices[idx]]

        # Extrair caracter√≠sticas (features) e r√≥tulos (labels)
        features = sample.drop(self.label_column).values
        label = sample[self.label_column]

        return features, label

In [195]:
# Exemplo de uso para conjunto de treinamento
dataset_treino = MeuDataset(data, label_column='Survived', train=True)

# Exemplo de uso para conjunto de teste
dataset_teste = MeuDataset(data, label_column='Survived', train=False)

# Criar DataLoaders para ambos os conjuntos
dataloader_treino = DataLoader(dataset_treino, batch_size=64, shuffle=True)
dataloader_teste = DataLoader(dataset_teste, batch_size=64, shuffle=False)

# Treinamento da rede

In [196]:
# Acesso a uma gpu Nvidia
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda

In [197]:
model = Rede().to(device)

In [198]:
# Fun√ß√£o de perda(Entropia Cruzada)
loss_func = nn.CrossEntropyLoss()
# Gradiente Descendente Estoc√°stico
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-3) # lr = taxa de aprendizado

In [199]:
def train(model, dataloader, loss_func, optimizer):
  model.train()
  cumloss = 0.0
  for x, y in dataloader:
    x = x.to(torch.float).to(device)
    y = y.to(torch.long).to(device)

    pred = model(x)
    loss = loss_func(pred, y)

    # Zera o gradiente
    optimizer.zero_grad()
    # Calcula o gradiente
    loss.backward()
    # Anda na dire√ß√£o que reduz a fun√ß√£o de perda
    optimizer.step()

    # Loss √© um tensor
    cumloss += loss.item()

  return cumloss/len(dataloader)

def teste(model, dataloader, loss_func):
  model.eval()
  cumloss = 0.0
  with torch.no_grad():
    for x, y in dataloader:
      x = x.to(torch.float).to(device)
      y = y.to(torch.long).to(device)

      pred = model(x)
      loss = loss_func(pred, y)

      # Loss √© um tensor
      cumloss += loss.item()

  return cumloss/len(dataloader)

In [200]:
epochs = 500
for t in range(epochs):
  train_loss = train(model, dataloader_treino, loss_func, optimizer)
  if t % 10 == 0:
    print(f'√âpoca = {t}, Erro de treinamento = {train_loss}')

test_loss = teste(model, dataloader_teste, loss_func)
print(f'Erro do teste = {test_loss}')

√âpoca = 0, Erro de treinamento = 9.464274803797403
√âpoca = 10, Erro de treinamento = 0.6560236612955729
√âpoca = 20, Erro de treinamento = 0.6311701536178589
√âpoca = 30, Erro de treinamento = 0.5962682366371155
√âpoca = 40, Erro de treinamento = 0.6184111833572388
√âpoca = 50, Erro de treinamento = 0.6486605604489645
√âpoca = 60, Erro de treinamento = 0.6515510082244873
√âpoca = 70, Erro de treinamento = 0.6311893264452616
√âpoca = 80, Erro de treinamento = 0.6974822481473287
√âpoca = 90, Erro de treinamento = 0.6036632855733236
√âpoca = 100, Erro de treinamento = 0.5768293738365173
√âpoca = 110, Erro de treinamento = 0.63606725136439
√âpoca = 120, Erro de treinamento = 0.6053340633710226
√âpoca = 130, Erro de treinamento = 0.5616122682889303
√âpoca = 140, Erro de treinamento = 0.6208042899767557
√âpoca = 150, Erro de treinamento = 0.6002313097318014
√âpoca = 160, Erro de treinamento = 0.5811314384142557
√âpoca = 170, Erro de treinamento = 0.5798573096593221
√âpoca = 180, Erro de treinamento = 0.5657606422901154
√âpoca = 190, Erro de treinamento = 0.602807899316152
√âpoca = 200, Erro de treinamento = 0.6176968216896057
√âpoca = 210, Erro de treinamento = 0.5727514227231344
√âpoca = 220, Erro de treinamento = 0.5813214778900146
√âpoca = 230, Erro de treinamento = 0.616809089978536
√âpoca = 240, Erro de treinamento = 0.6094286243120829
√âpoca = 250, Erro de treinamento = 0.5734389126300812
√âpoca = 260, Erro de treinamento = 0.5892439484596252
√âpoca = 270, Erro de treinamento = 0.5683704614639282
√âpoca = 280, Erro de treinamento = 0.5584913492202759
√âpoca = 290, Erro de treinamento = 0.5912624398867289
√âpoca = 300, Erro de treinamento = 0.5855413277943929
√âpoca = 310, Erro de treinamento = 0.5597631533940634
√âpoca = 320, Erro de treinamento = 0.5564673145612081
√âpoca = 330, Erro de treinamento = 0.5604073603947958
√âpoca = 340, Erro de treinamento = 0.5514012376467387
√âpoca = 350, Erro de treinamento = 0.5758072336514791
√âpoca = 360, Erro de treinamento = 0.5671726862589518
√âpoca = 370, Erro de treinamento = 0.5519816279411316
√âpoca = 380, Erro de treinamento = 0.5616415937741598
√âpoca = 390, Erro de treinamento = 0.5901629130045573
√âpoca = 400, Erro de treinamento = 0.5879435737927755
√âpoca = 410, Erro de treinamento = 0.593386153380076
√âpoca = 420, Erro de treinamento = 0.564890444278717
√âpoca = 430, Erro de treinamento = 0.5755303899447123
√âpoca = 440, Erro de treinamento = 0.606173058350881
√âpoca = 450, Erro de treinamento = 0.5703271230061849
√âpoca = 460, Erro de treinamento = 0.5687525868415833
√âpoca = 470, Erro de treinamento = 0.5760896603266398
√âpoca = 480, Erro de treinamento = 0.5887962182362875
√âpoca = 490, Erro de treinamento = 0.6128785411516825
Erro do teste = 0.5765824317932129